spring.application.name=order

server.port=8082

# H2 Database Config (Separate DB from Inventory)
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console Config (Access at http://localhost:8082/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Liquibase (Disable for now to avoid classpath errors, use schema.sql/data.sql instead)
spring.liquibase.enabled=false

# Inventory Service URL (Used by RestClient/RestTemplate)
inventory.service.url=http://localhost:8081/inventory

spring.sql.init.mode=always
# Agar table already auto-update se ban rahi hai toh:
spring.jpa.hibernate.ddl-auto=none
